### ISSUE TITLE
[map_builder_node-1] NO EFFECTIVE POINTS!

### ISSUE THREAD

**Issue by ZhouJiafen** [liangheming/iG-LIO_SAM_LC#1]
您好，我参考您的代码将此项目修改为ros2的版本，运行时gicpConstraint函数报错[map_builder_node-1] NO EFFECTIVE POINTS!建图也是漂移的，可以帮忙分析一下可能的原因是什么吗

**Comment by ZhouJiafen** [comment]
已解决，时间戳问题

**Comment by liangheming** [comment]
好的，非常感谢您的相关工作，如果您愿意的话，希望可以给出一些版本切换的建议，以帮助更多的人

**Comment by liangheming** [comment]
> 已解决，时间戳问题

好的，非常感谢您的相关工作，如果您愿意的话，希望可以给出一些版本切换的建议，以帮助更多的人

**Comment by ZhouJiafen** [comment]
> > 已解决，时间戳问题
> 
> 好的，非常感谢您的相关工作，如果您愿意的话，希望可以给出一些版本切换的建议，以帮助更多的人

框架还在学习中，很多还不懂！转ros2版本需要注意两者时间上的写法不同double timestamp = msg->header.stamp.toSec();改写成double timestamp = msg->header.stamp.sec + msg->header.stamp.nanosec * 1e-9;
我是工作需要，后期会增加机械雷达的适配和高频定位的工程化，这些我还不熟悉，在慢慢实现中
