### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by NCEPUMarBle** [liangheming/iG-LIO_SAM_LC#4]
大佬您好，我想问一下，编译的时候SOPHUS出错，如下：
/home/iglio_ws/src/iG-LIO_SAM_LC/src/ieskf/ieskf.cpp: In function ‘Eigen::Matrix3d kf::rightJacobian(const Vector3d&)’:
/home/iglio_ws/src/iG-LIO_SAM_LC/src/ieskf/ieskf.cpp:8:30: error: ‘leftJacobian’ is not a member of ‘Sophus::SO3d’ {aka ‘Sophus::SO3<double>’}
    8 |         return Sophus::SO3d::leftJacobian(inp).transpose();
      |                              ^~~~~~~~~~~~
没找到解决办法，麻烦您能看一下不

**Comment by liangheming** [comment]
应该是Sophus版本的问题，你的Sophus的版本没有leftJacobian这个方法，可以用sohpus 的 1.22.10这个版本试一下

**Comment by NCEPUMarBle** [comment]
已解决，感谢！

**Comment by liangheming** [comment]
版本问题
