### ISSUE TITLE
The question about the Jacobian derivation in IESKF::update()?

### ISSUE THREAD

**Issue by Freeecode** [liangheming/iG-LIO_SAM_LC#7]
Hi, thanks for sharing the work! I was checking the code and  found some difference compared to ig-lio, especially in convariance update and constructing IMU prior constraint. For example, when constructing IMU prior constraint,  the jacobian about current state in ig-lio is  
![image](https://github.com/liangheming/iG-LIO_SAM_LC/assets/28192066/2210f63d-45e5-4c9d-a736-39ebef74345f)
while in your code is
![image](https://github.com/liangheming/iG-LIO_SAM_LC/assets/28192066/fda9d044-c927-4b97-b9ae-4db88de1e91c)
and I checked the details in the paper  and other paper: 
![image](https://github.com/liangheming/iG-LIO_SAM_LC/assets/28192066/d2af219b-b6a7-4573-886a-b3d7e37c1caf)
and the problem also appear in convariance update, in ig-lio:
![image](https://github.com/liangheming/iG-LIO_SAM_LC/assets/28192066/8866ceab-3341-48c2-aa08-fead6294efe1)
while in  in your code :
![image](https://github.com/liangheming/iG-LIO_SAM_LC/assets/28192066/c484ee46-3bef-44cc-973e-c238627e3c4c)
if the LIO is ok, I think the jacobian maybe is approximately identity matrix.

**Comment by liangheming** [comment]
Thank you for your careful inspection，you are right,  I have really made a big mistake.  it should be "Jr_inv", not "Jr";

![a](https://github.com/liangheming/iG-LIO_SAM_LC/assets/21339484/bc032f69-3663-49f2-a2aa-c107960035e2)

**Comment by Freeecode** [comment]
Hi, the functions of convariance update are aslo different. I checked the formulation in ig-lio and I found that  is similar to -Jl_inv:
![image](https://github.com/liangheming/iG-LIO_SAM_LC/assets/28192066/842000cd-9458-4ec3-8ce7-10a98d7bfdd1)
about this question, do you have any ideas?

**Comment by liangheming** [comment]
i think the author missed a transpose(),  P_ = L.transpose() * temp * L

**Comment by Freeecode** [comment]
yes, in the ig-lio code, the author missed a transpose for L, and the computation of matrix L confused me, which is a derivation of state?

**Comment by liangheming** [comment]
![reply](https://github.com/liangheming/iG-LIO_SAM_LC/assets/21339484/c06cba01-5a80-4ed6-9fe4-49a5d7c790f4)

**Comment by Freeecode** [comment]
用中文吧，整个过程是我是清楚，就是在计算L矩阵时，我看需要计算雅克比矩阵，如下图所示
![image](https://github.com/liangheming/iG-LIO_SAM_LC/assets/28192066/1b8ae6ef-0bc8-41b7-8029-6406a9a13a19)
而在你的代码中，这部分也在计算雅克比矩阵
![image](https://github.com/liangheming/iG-LIO_SAM_LC/assets/28192066/0f81347a-c3cf-47fb-9dc4-98f4b00f336e)
ig-lio中L的计算，这个雅克比的形式应该是Jl_inv，这个雅克比矩阵应该是对更新之前的位姿进行求导

**Comment by liangheming** [comment]
最后一步是误差卡尔曼的修正过程，在[《Quaternion kinematics for the error-state KF》](https://arxiv.org/pdf/1711.02508) 第64页的6.3节ESKF reset有直接的结论, IG LIO 的作者应该是用了这里的结论，但是这个雅可比其实误差状态对更新前误差的导数(文字描述还是有歧义，你直接看论文中的公式，或许会更好理解)

**Comment by Freeecode** [comment]
好的，谢谢！
