### ISSUE TITLE
有运行的效果展示图么？

### ISSUE THREAD

**Issue by goldtimes** [liangheming/iG-LIO_SAM_LC#9]

**Comment by liangheming** [comment]
这个可能需要你自己编译运行一下了，repo里有demo数据包，你可以跑一下试试，我因一些原因，暂时没法补充运行效果

**Comment by goldtimes** [comment]
![Uploading 截图 2024-06-25 20-34-03.png…]()

**Comment by goldtimes** [comment]
![截图 2024-06-25 20-34-03](https://github.com/liangheming/iG-LIO_SAM_LC/assets/17950509/5eb97868-8589-47bb-b0b5-f062d2331b5e)

**Comment by goldtimes** [comment]
效果还是不错的，挺稳的

**Comment by liangheming** [comment]
好的，感谢提供效果图
